"""add_contact_phone

Revision ID: 9f8g7h6i5j4k
Revises: 02e74cc7cf57
Create Date: 2026-08-01 10:30:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f8g7h6i5j4k'
down_revision = '02e74cc7cf57'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('marketplace_listings', sa.Column('contact_phone', sa.String(), nullable=True))
    op.add_column('job_listings', sa.Column('contact_phone', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job_listings', 'contact_phone')
    op.drop_column('marketplace_listings', 'contact_phone')
    # ### end Alembic commands ###
