"""Add soft delete and moderation columns

Revision ID: a5e4fa3b94d3
Revises: 60d9c4348826
Create Date: 2026-08-05 12:43:32.718596

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a5e4fa3b94d3'
down_revision: Union[str, Sequence[str], None] = '60d9c4348826'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_messages', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('chat_messages', sa.Column('deleted_by_admin', sa.Boolean(), nullable=True))
    op.add_column('chat_messages', sa.Column('delete_reason', sa.String(), nullable=True))
    op.alter_column('chat_messages', 'content',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('chat_messages', 'mentions',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('chat_messages', 'translated_text',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.create_index('idx_chat_room_created', 'chat_messages', ['room_id', 'created_at'], unique=False, postgresql_using='btree')
    op.create_index(op.f('ix_chat_messages_created_at'), 'chat_messages', ['created_at'], unique=False)
    op.create_index(op.f('ix_chat_messages_room_id'), 'chat_messages', ['room_id'], unique=False)
    op.create_index(op.f('ix_chat_messages_sender_id'), 'chat_messages', ['sender_id'], unique=False)
    op.create_foreign_key(None, 'chat_messages', 'chat_messages', ['reply_to_id'], ['id'])
    op.create_foreign_key(None, 'emergencies', 'users', ['assigned_to'], ['id'])
    op.drop_column('emergencies', 'radius_escalation')
    op.add_column('events', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('events', sa.Column('deleted_by_admin', sa.Boolean(), nullable=True))
    op.add_column('events', sa.Column('delete_reason', sa.String(), nullable=True))
    op.create_index(op.f('ix_events_status'), 'events', ['status'], unique=False)
    op.create_foreign_key(None, 'events', 'chat_rooms', ['chat_room_id'], ['id'])
    op.create_index(op.f('ix_marketplace_listings_category'), 'marketplace_listings', ['category'], unique=False)
    op.create_index(op.f('ix_marketplace_listings_created_at'), 'marketplace_listings', ['created_at'], unique=False)
    op.create_index(op.f('ix_marketplace_listings_status'), 'marketplace_listings', ['status'], unique=False)
    op.create_foreign_key(None, 'news', 'users', ['verified_by'], ['id'])
    op.add_column('polls', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('polls', sa.Column('deleted_by_admin', sa.Boolean(), nullable=True))
    op.add_column('polls', sa.Column('delete_reason', sa.String(), nullable=True))
    op.add_column('products', sa.Column('bulk_price', sa.Float(), nullable=True))
    op.add_column('products', sa.Column('stock', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_products_price'), 'products', ['price'], unique=False)
    op.alter_column('profiles', 'bio',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.add_column('shops', sa.Column('is_open', sa.Boolean(), nullable=True))
    op.add_column('shops', sa.Column('delivery_available', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_shops_is_approved'), 'shops', ['is_approved'], unique=False)
    op.create_index(op.f('ix_shops_is_verified'), 'shops', ['is_verified'], unique=False)
    op.add_column('tournaments', sa.Column('payment_link', sa.String(), nullable=True))
    op.add_column('tournaments', sa.Column('chat_room_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'tournaments', 'chat_rooms', ['chat_room_id'], ['id'])
    op.drop_index(op.f('idx_users_mid'), table_name='users')
    op.drop_index(op.f('idx_users_username_lower'), table_name='users')
    op.drop_constraint(op.f('users_mid_key'), 'users', type_='unique')
    op.drop_constraint(op.f('users_username_key'), 'users', type_='unique')
    op.create_index(op.f('ix_users_mid'), 'users', ['mid'], unique=True)
    op.create_index(op.f('ix_users_uid'), 'users', ['uid'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_uid'), table_name='users')
    op.drop_index(op.f('ix_users_mid'), table_name='users')
    op.create_unique_constraint(op.f('users_username_key'), 'users', ['username'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('users_mid_key'), 'users', ['mid'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_users_username_lower'), 'users', [sa.literal_column('lower(username::text)')], unique=False)
    op.create_index(op.f('idx_users_mid'), 'users', ['mid'], unique=False)
    op.drop_constraint(None, 'tournaments', type_='foreignkey')
    op.drop_column('tournaments', 'chat_room_id')
    op.drop_column('tournaments', 'payment_link')
    op.drop_index(op.f('ix_shops_is_verified'), table_name='shops')
    op.drop_index(op.f('ix_shops_is_approved'), table_name='shops')
    op.drop_column('shops', 'delivery_available')
    op.drop_column('shops', 'is_open')
    op.alter_column('profiles', 'bio',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_index(op.f('ix_products_price'), table_name='products')
    op.drop_column('products', 'stock')
    op.drop_column('products', 'bulk_price')
    op.drop_column('polls', 'delete_reason')
    op.drop_column('polls', 'deleted_by_admin')
    op.drop_column('polls', 'deleted_at')
    op.drop_constraint(None, 'news', type_='foreignkey')
    op.drop_index(op.f('ix_marketplace_listings_status'), table_name='marketplace_listings')
    op.drop_index(op.f('ix_marketplace_listings_created_at'), table_name='marketplace_listings')
    op.drop_index(op.f('ix_marketplace_listings_category'), table_name='marketplace_listings')
    op.drop_constraint(None, 'events', type_='foreignkey')
    op.drop_index(op.f('ix_events_status'), table_name='events')
    op.drop_column('events', 'delete_reason')
    op.drop_column('events', 'deleted_by_admin')
    op.drop_column('events', 'deleted_at')
    op.add_column('emergencies', sa.Column('radius_escalation', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'emergencies', type_='foreignkey')
    op.drop_constraint(None, 'chat_messages', type_='foreignkey')
    op.drop_index(op.f('ix_chat_messages_sender_id'), table_name='chat_messages')
    op.drop_index(op.f('ix_chat_messages_room_id'), table_name='chat_messages')
    op.drop_index(op.f('ix_chat_messages_created_at'), table_name='chat_messages')
    op.drop_index('idx_chat_room_created', table_name='chat_messages', postgresql_using='btree')
    op.alter_column('chat_messages', 'translated_text',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('chat_messages', 'mentions',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('chat_messages', 'content',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_column('chat_messages', 'delete_reason')
    op.drop_column('chat_messages', 'deleted_by_admin')
    op.drop_column('chat_messages', 'deleted_at')
    # ### end Alembic commands ###
