"""Check missing columns

Revision ID: ea12b090ad39
Revises: a5e4fa3b94d3
Create Date: 2026-08-07 19:03:38.818696

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea12b090ad39'
down_revision: Union[str, Sequence[str], None] = 'a5e4fa3b94d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_users_mid'), table_name='users')
    op.drop_index(op.f('idx_users_username_lower'), table_name='users')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_users_username_lower'), 'users', [sa.literal_column('lower(username::text)')], unique=False)
    op.create_index(op.f('idx_users_mid'), 'users', ['mid'], unique=False)
    # ### end Alembic commands ###
