name: Keep Render Awake

on:
  schedule:
    - cron: '*/14 * * * *' # Runs every 14 minutes
  workflow_dispatch: # Allows manual trigger

jobs:
  ping_render:
    runs-on: ubuntu-latest
    steps:
      - name: Ping My Harur Render Service
        run: curl -s https://myharur.onrender.com/ > /dev/null
